version: '3.8'

services:
  mynginx:
    build: .
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/var/www/html:ro
    restart: unless-stopped
